# Here I am defining a function called "animation" that contains the animation shown in the game as the player play through the game

def animation(lives):
    if lives == 11:
        print("\nYou have " + str(lives) + " lives left.")
        print("_______  ")
        print("|     |  ")
        print("|        ")
        print("|        ")
        print("|        ")
        print("|        ")
        print("|        ")
        print("|        ")
    if lives == 10:
        print("\nYou have " + str(lives) + " lives left.")
        print("_______  ")
        print("|     |  ")
        print("|     O  ")
        print("|        ")
        print("|        ")
        print("|        ")
        print("|        ")
        print("|        ")
    if lives == 9:
        print("\nYou have " + str(lives) + " lives left.")
        print("_______  ")
        print("|     |  ")
        print("|     O  ")
        print("|     |  ")
        print("|        ")
        print("|        ")
        print("|        ")
        print("|        ")
    if lives == 8:
        print("\nYou have " + str(lives) + " lives left.")
        print("_______  ")
        print("|     |  ")
        print("|     O  ")
        print("|     |  ")
        print("|     |  ")
        print("|        ")
        print("|        ")
        print("|        ")
    if lives == 7:
        print("\nYou have " + str(lives) + " lives left.")
        print("_______  ")
        print("|     |  ")
        print("|     O  ")
        print("|    /|  ")
        print("|     |  ")
        print("|        ")
        print("|        ")
        print("|        ")
    if lives == 6:
        print("\nYou have " + str(lives) + " lives left.")
        print("_______  ")
        print("|     |  ")
        print("|     O  ")
        print("|    /|\ ")
        print("|     |  ")
        print("|        ")
        print("|        ")
        print("|        ")
    if lives == 5:
        print("\nYou have " + str(lives) + " lives left.")
        print("_______  ")
        print("|     |  ")
        print("|     O  ")
        print("|    /|\ ")
        print("|   / |  ")
        print("|        ")
        print("|        ")
        print("|        ")
    if lives == 4:
        print("\nYou have " + str(lives) + " lives left.")
        print("_______  ")
        print("|     |  ")
        print("|     O  ")
        print("|    /|\ ")
        print("|   / | \ ")
        print("|        ")
        print("|        ")
        print("|        ")
    if lives == 3:
        print("\nYou have " + str(lives) + " lives left.")
        print("_______  ")
        print("|     |  ")
        print("|     O  ")
        print("|    /|\ ")
        print("|   / | \ ")
        print("|    /   ")
        print("|        ")
        print("|        ")
    if lives == 2:
        print("\nYou have " + str(lives) + " lives left.")
        print("_______  ")
        print("|     |  ")
        print("|     O  ")
        print("|    /|\ ")
        print("|   / | \ ")
        print("|    /   ")
        print("|   /    ")
        print("|        ")
    if lives == 1:
        print("\nYou have " + str(lives) + " lives left.")
        print("_______  ")
        print("|     |  ")
        print("|     O  ")
        print("|    /|\ ")
        print("|   / | \ ")
        print("|    / \ ")
        print("|   /    ")
        print("|        ")
    if lives == 0:
        print("\nYou have " + str(lives) + " lives left.")
        print("_______  ")
        print("|     |  ")
        print("|     O  ")
        print("|    /|\ ")
        print("|   / | \ ")
        print("|    / \ ")
        print("|   /   \ ")
        print("|        ")
        print("Sorry you didn't guess the word in time, so the guy died.")
